let theString = "  Ahmed ali mohamed  ";
console.log(theString);
console.log(theString[1]);
console.log(theString.charAt(1));
console.log(theString.length);
console.log(theString.trim());
console.log(theString.trim().charAt(2).toUpperCase());
console.log(theString.indexOf("m"));
console.log(theString.lastIndexOf("m"));
console.log(theString.slice(12, 19));
console.log(theString.slice(-9, -2));
console.log(theString.repeat(2));
console.log(theString.split(" "));
console.log(theString.length);
console.log(theString.substring(2, 7));
console.log(theString.substring(theString.length - 9, theString.length - 2));
console.log(theString.substr(2, 5));
console.log(theString.substr(-9, 7));
console.log(theString.includes("ali"));
console.log(theString.includes("alii"));
console.log(theString.startsWith("A", 2));
console.log(theString.startsWith("Ahmed", 2));
console.log(theString.endsWith("d", 7));
